# Generated by Django 5.0.6 on 2024-07-11 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_monthyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthyear',
            old_name='monthYear',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='monthyear',
            unique_together={('user', 'date')},
        ),
    ]
